[package]
name = "turbin3-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.15.2"
borsh = "0.10.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
solana-client = "1.7.14"
